services:
  apache:
    image: php:8.2-apache
    volumes:
      - appdata:/var/www/html
    ports:
      - "80:80"

  devlinux:
    image: dorowu/ubuntu-desktop-lxde-vnc
    volumes:
      - appdata:/workspace
    ports:
      - "6080:80"
      - "8090:8080"
      - "5901:5901"
    environment:
      - VNC_PASSWORD=devpass
      - RESOLUTION=1536x960
    shm_size: "2gb"

volumes:
  appdata:
